name: Build and deploy

env:
  AZURE_WEBAPP_NAME: nuclea-kendo-demo
  WORK_DIR: server   
  NODE_VERSION: '22.x'  

  
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    permissions:
      contents: read
      id-token: write    
    environment: 'Production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.WORK_DIR }}
          startup-command: 'npm start'
          
      - name: logout
        run: |
          az logout
        