name: Build and deploy

env:
  AZURE_WEBAPP_NAME: nuclea-kendo-demo
  WORK_DIR: server   
  NODE_VERSION: '22.x'  

  
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    
    defaults:
      run:
        working-directory: ${{ env.WORK_DIR }}

    permissions:
      contents: read
      id-token: write    
    environment: 'Production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies and build
        run: |
          cd server
          npm install
          cd ..   
                

      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.WORK_DIR  }}
          
      - name: logout
        run: |
          az logout
        